repos:

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.8.2
    hooks:
      - id: reorder-python-imports

  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        args:
          - --line-length=119

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.37.2
    hooks:
      - id: pyupgrade

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.220
    hooks:
      - id: ruff
        args:
          - --line-length=119
        additional_dependencies:
          - flake8-bugbear==21.11.29
          - flake8-builtins==1.5.3
          - pep8-naming==0.12.1
          - flake8-variables-names==0.0.4
          - flake8-commas==2.1.0
          - flake8-mock==0.3
          - flake8-printf-formatting==1.1.2
          - flake8-use-fstring==1.3
          - flake8-pytest-style==1.5.1
          - flake8-simplify==0.14.2
          - flake8-walrus==1.1.0
          - flake8-annotations==2.7.0

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-docstring-first
      - id: check-json
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: name-tests-test
      - id: requirements-txt-fixer
      - id: end-of-file-fixer
        exclude: ^data/
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md

  - repo: https://github.com/jendrikseipp/vulture
    rev: v2.5
    hooks:
      - id: vulture
        args:
          - ./
          - --exclude=env/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
      - id: mypy

  - repo: https://github.com/ComPWA/mirrors-pyright
    rev: v1.1.261
    hooks:
      - id: pyright
