name: ci

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ master ]

jobs:

  pre_commit:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10.0]

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: run pre-commit action
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: --all-files

      - name: run tests
        run: |
          python -m pytest tests/ -v
